HashMap<Landmark, Point> landmarks = new HashMap<Landmark, Point>();

enum Landmark {
  CENTER_NECKLINE,
  CENTER_WAIST,
  OUTER_WAIST,
  COLLAR,
  SHOULDER,
  SHOULDER_ANCHOR,
  BUST_APEX,
  ARMPIT,
  CHEST_ANCHOR,
  ARMPIT_ANCHOR,
  DART_TIP,
  DART_START,
  DART_END,
  BACK_CENTER_NECKLINE,
  BACK_CENTER_WAIST,
  BACK_OUTER_WAIST,
  BACK_COLLAR,
  BACK_SHOULDER,
  BACK_SHOULDER_ANCHOR,
  BACK_ARMPIT,
  BACK_ARMPIT_ANCHOR,
  BACK_CHEST_ANCHOR,
  BACK_SHOULDER_DART_TIP,
  BACK_SHOULDER_DART_START,
  BACK_SHOULDER_DART_END,
  BACK_WAIST_DART_TIP,
  BACK_WAIST_DART_START,
  BACK_WAIST_DART_END,
}

Point valueOf(Landmark landmark) {
  return landmarks.get(landmark);
}
